[package]
name = "starberry_core"
version = "0.2.0"
edition = "2024"
authors = ["Redstone <redstone@fds.moe>"] 
description = "A framework for building web applocation in Rust" 
license = "MIT" 
repository = "https://github.com/Redstone-D/starberry" 

[dependencies] 
regex = "1.5.6" 
tokio = { version = "1.28", features = ["full"] } 
futures = "0.3" 
