[package]
name = "starberry_middlewares"
version = "0.1.0"
edition = "2024"

[dependencies]
starberry_macro = { path = "../sm", version="0.4"} 
starberry_core = { path = "../starberry_core", version="0.4" }  
starberry = { path = "../starberry", version="0.4" }  