[package]
name = "starberry"
version = "0.3.1-rc2"
edition = "2024"
authors = ["Redstone <redstone@fds.moe>"] 
description = "Small, sweet, easy framework for full-stack web application" 
license = "MIT" 
repository = "https://github.com/Redstone-D/starberry" 
categories = ["network-programming", "web-programming::http-server" ]
keywords = ["full-stack", "web-framework", "starberry"] 

[dependencies] 
akari = "0.1.1" 
regex = "1.5.6" 
tokio = { version = "1.28", features = ["full"] } 
futures = "0.3" 
once_cell = "1.10.0" 
starberry_macro = { path = "../sm", version="0.2.2"} 
starberry_core = { path = "../starberry_core", version="0.3.1" } 
ctor = "0.4.0" 
